#sudo: false

language: android

jdk:
  - oraclejdk8

branches:
  only:
  #- master

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-25.0.2
    # The SDK version used to compile your project
    - android-25

    # Additional components
    #- extra-google-google_play_services
    #- extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

script:
- ./gradlew assembleRelease
